language: python
python:
  - 3.9
script:
  - black --check .
  - flake8 --max-line-length=88 .
  - coverage run manage.py test
install:
  - pip install -r requirements.txt
after_success:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: mysite-polls-app-dev
  env: mysite-polls-app-dev-env
  bucket_name: elasticbeanstalk-us-east-1-783764614931
  on:
    branch: main
branches:
  only:
    - main
